version: '3'
services:
  chromadb:
    image: chromadb/chroma:latest
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ${VOLUMEN_CHROMADB}:/chroma/chroma
    environment:
      - ALLOW_RESET=TRUE
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    networks:
      red_llm:
        ipv4_address: 172.18.0.2

  ollama:
    image: ollama/ollama:latest
    restart: always
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    networks:
      red_llm:
        ipv4_address: 172.18.0.3

  rag:
    image: mcortes027/alina_rag:latest
    #entrypoint: ["tail", "-f", "/dev/null"]
    entrypoint: ["python3", "/app/rag/UnityConnector.py"]
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ${VOLUMEN_CODE}:/app
      - ${VOLUMEN_AUDIO}:/audio
    networks:
      red_llm:
        ipv4_address: 172.18.0.5  
networks:
  red_llm:
    ipam:
      config:
        - subnet: 172.18.0.0/16
  web:
    external: false

