name: ci
# Crea las imagenes
on: 
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
    - main
jobs:
  build:
    runs-on: self-hosted
    steps:        
    - name: docker build rag image
      working-directory: /work/alina/alina/app
      run: sudo docker build -t mcortes027/alina_rag:latest .
      
    - name: docker build runner image
      working-directory: /work/alina/alina/despliegues/git-runner
      run: sudo docker build -t mcortes027/ceiabda_runner:latest .
